version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql

  mssql:
    image: microsoft/mssql-server-linux
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: sa_Password
      ACCEPT_EULA: Y
    volumes:
      - mssql_volume:/var/opt/mssql/data

  anaconda:
    build:
      context: ./anaconda/
    container_name: anaconda
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ../jupyter_notebooks:/notebooks/

volumes:
  mysql_volume:
  mssql_volume: