version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql-volume:/var/lib/mysql

  anaconda:
    build:
      context: ./anaconda/
    container_name: anaconda
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ../jupyter_notebooks:/notebooks/